import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ReduxProvider } from "@/redux/provider";

import "./globals.css";
import Sidebar2 from "@/components/sidebar/Sidebar";
import Header from "@/components/header/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-bg_accent`}>
        <ReduxProvider>
        <div className="">
      <div className="flex min-h-screen w-full flex-col bg-muted/40">
        <Header />
        <Sidebar2/>
        <main className="md:ml-[69px] pr-2 mt-2 max-md:px-2">{children}</main>
      </div>
    </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
